### PR TITLE
Readying for release on rubygems

### PR DESCRIPTION
**Pull request by knightsamar**
Fixes : #26, #25, #24, #21 and also #27 except for the tagging part which I will do once this PR is merged.

### CODE REVIEW

**Comment by knightsamar** [comment]
@ramereth @DesertBeagle going by http://semver.org/#semantic-versioning-specification-semver, would you suggest we number the version as 1.0.0 ? I think the command-line API is quite stable and the Ruby API won't see any major changes any soon since it works quite well after our last overhaul.

**Review by eldebrim — APPROVED** [review]

**Review by Codysseus — APPROVED** [review]

**Comment by Codysseus** [comment]
@knightsamar Yup! I think 1.0.0 is a good version number for what we have.

**Comment by knightsamar** [comment]
@ramereth can I have your review please ?

**Review by ramereth — APPROVED** [review]

**Comment by knightsamar** [comment]
Thanks!

**Pull request merged**
